
services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"  # Permet à l'agent d'accéder directement au réseau de l'hôte
    restart: always
    volumes:
      - ./logs:/app/logs
    environment:
      - SITE_ID=${SITE_ID:-default}
      - API_URL=${API_URL:-https://api.example.com}

