// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abydmizlmqhwzsyrpjmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieWRtaXpsbXFod3pzeXJwam1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjE4MDQsImV4cCI6MjA1NTUzNzgwNH0.rRC0Pv6kDOw4_pxKBfaV1n_PaMSiZJ-RHFz3yMMc5CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);